language: go

go:
  - 1.2
  - tip

before_install:
  - sudo apt-get install -qq -y libsdl1.2debian
  - sudo apt-get install -qq -y libsdl-image1.2-dev
  - ./install_go_sdl.sh

install: 
  - go get code.google.com/p/go.tools/cmd/cover

script: go test -v -cover ./...
